from __future__ import annotations

from pathlib import Path

from fastapi.testclient import TestClient

from opencomp.app import app
from opencomp.cli import main, parse_frame_range
from opencomp.core.models import Edge, Node, Project, ProjectGraph, ProjectSettings, ScriptTab
from opencomp.core.project_io import load_project_file, save_project_file
from opencomp.io.nuke_exporter import build_nuke_script


def test_parse_frame_range_supports_single_ranges_lists_and_steps() -> None:
    assert parse_frame_range("1001", 1, 1) == [1001]
    assert parse_frame_range("1001-1003", 1, 1) == [1001, 1002, 1003]
    assert parse_frame_range("1001,1003,1005", 1, 1) == [1001, 1003, 1005]
    assert parse_frame_range("1001-1006x2", 1, 1) == [1001, 1003, 1005]
    assert parse_frame_range(None, 1008, 1010) == [1008]


def test_project_api_save_load_and_export_nuke_script(tmp_path: Path) -> None:
    client = TestClient(app)
    project = client.post("/api/projects/new").json()
    project["project_name"] = "Disk Test"

    save_response = client.post("/api/projects/save", json={"path": str(tmp_path / "disk_test"), "project": project})
    assert save_response.status_code == 200
    saved = save_response.json()
    assert saved["settings"]["project_path"].endswith(".opencomp")
    assert (tmp_path / "disk_test.opencomp").exists()

    load_response = client.post("/api/projects/load", json={"path": str(tmp_path / "disk_test.opencomp")})
    assert load_response.status_code == 200
    assert load_response.json()["project_name"] == "Disk Test"

    export_response = client.post("/api/projects/export-nuke", json={"path": str(tmp_path / "disk_test.nk")})
    assert export_response.status_code == 200
    assert export_response.json()["status"] == "exported"
    nuke_text = (tmp_path / "disk_test.nk").read_text(encoding="utf-8")
    assert "version 16.0 v6" in nuke_text
    assert "Root {" in nuke_text
    assert "Read {" in nuke_text
    assert "Grade {" in nuke_text
    assert "Viewer {" in nuke_text

    content_response = client.post("/api/projects/export-nuke/content", json={"path": "browser_export.nk"})
    assert content_response.status_code == 200
    assert "Generated by OpenComp Studio Nuke exporter v1" in content_response.text
    assert "Viewer {" in content_response.text


def test_project_io_round_trip_uses_opencomp_extension(tmp_path: Path) -> None:
    project = _constant_write_project(tmp_path)
    output_path = save_project_file(project, tmp_path / "roundtrip")
    assert output_path.name == "roundtrip.opencomp"

    loaded = load_project_file(tmp_path / "roundtrip")
    assert loaded.settings.project_path == str(output_path)
    assert loaded.graph.nodes["Write1"].params["path"].endswith("render.####.png")


def test_project_api_import_project_data_resets_backend_session(tmp_path: Path) -> None:
    client = TestClient(app)
    project = _constant_write_project(tmp_path)
    project.project_name = "Imported From Browser"
    project.settings.project_path = None

    response = client.post("/api/projects/import", json={"project": project.model_dump(mode="json")})

    assert response.status_code == 200
    imported = response.json()
    assert imported["project_name"] == "Imported From Browser"
    assert imported["graph"]["nodes"]["Write1"]["params"]["path"].endswith("render.####.png")
    assert imported["settings"]["project_path"] is None


def test_project_save_prefers_top_level_active_graph_payload(tmp_path: Path) -> None:
    project = _constant_write_project(tmp_path)
    project.script_tabs[0].graph = project.graph.model_copy(deep=True)
    project.script_tabs[0].graph.nodes["Write1"].params["path"] = str(tmp_path / "stale.####.png")
    project.graph.nodes["Write1"].params["path"] = str(tmp_path / "fresh.####.png")

    output_path = save_project_file(project, tmp_path / "fresh_graph")
    loaded = load_project_file(output_path)

    assert loaded.graph.nodes["Write1"].params["path"].endswith("fresh.####.png")
    assert loaded.script_tabs[0].graph.nodes["Write1"].params["path"].endswith("fresh.####.png")


def test_nuke_export_writes_stack_connections_for_merge(tmp_path: Path) -> None:
    graph = ProjectGraph(
        nodes={
            "ConstantA": Node(id="ConstantA", type="Constant", position=(0, 0), params={"r": 1.0, "a": 1.0}),
            "ConstantB": Node(id="ConstantB", type="Constant", position=(200, 0), params={"b": 1.0, "a": 1.0}),
            "Merge1": Node(id="Merge1", type="Merge", position=(100, 120), params={"operation": "add", "mix": 0.5}),
            "Viewer1": Node(id="Viewer1", type="Viewer", position=(100, 240), params={"active_input": "0"}),
        },
        edges=[
            Edge(id="a-merge", source_node="ConstantA", target_node="Merge1", target_socket="a"),
            Edge(id="b-merge", source_node="ConstantB", target_node="Merge1", target_socket="b"),
            Edge(id="merge-viewer", source_node="Merge1", target_node="Viewer1", target_socket="0"),
        ],
    )
    project = _project_from_graph(graph)

    nuke_text = build_nuke_script(project, tmp_path / "merge_test.nk")

    assert "Merge2 {" in nuke_text
    assert " operation plus" in nuke_text
    assert " mix 0.5" in nuke_text
    assert "push $OC_ConstantB\npush $OC_ConstantA\nMerge2 {" in nuke_text
    assert "set OC_Merge1 [stack 0]" in nuke_text


def test_nuke_export_uses_noop_for_unsupported_nodes(tmp_path: Path) -> None:
    graph = ProjectGraph(
        nodes={
            "Constant1": Node(id="Constant1", type="Constant", position=(0, 0), params={"a": 1.0}),
            "FutureNode1": Node(id="FutureNode1", type="FutureNode", position=(0, 120), params={"strength": 2}),
        },
        edges=[Edge(id="constant-future", source_node="Constant1", target_node="FutureNode1")],
    )
    project = _project_from_graph(graph)

    nuke_text = build_nuke_script(project, tmp_path / "unsupported_test.nk")

    assert "NoOp {" in nuke_text
    assert 'label "OpenComp unsupported node: FutureNode' in nuke_text
    assert "push $OC_Constant1\nNoOp {" in nuke_text


def test_cli_renders_write_node_from_opencomp_project(tmp_path: Path) -> None:
    project = _constant_write_project(tmp_path)
    project_path = save_project_file(project, tmp_path / "cli_project")

    exit_code = main([str(project_path), "--render", "Write1", "--range", "1001-1002", "--json"])

    assert exit_code == 0
    assert (tmp_path / "render.1001.png").exists()
    assert (tmp_path / "render.1002.png").exists()


def test_cli_can_run_script_and_save_project(tmp_path: Path) -> None:
    project = _constant_write_project(tmp_path)
    project_path = save_project_file(project, tmp_path / "script_project")
    saved_path = tmp_path / "script_project_updated.opencomp"

    exit_code = main(
        [
            str(project_path),
            "--eval",
            "opencomp.node('root').value('name').setValue('CLI Edited')",
            "--save",
            str(saved_path),
            "--export-nuke",
            str(tmp_path / "script_project_updated.nk"),
        ]
    )

    assert exit_code == 0
    loaded = load_project_file(saved_path)
    assert loaded.project_name == "CLI Edited"
    assert "Generated by OpenComp Studio Nuke exporter v1" in (tmp_path / "script_project_updated.nk").read_text(
        encoding="utf-8"
    )


def _constant_write_project(tmp_path: Path) -> Project:
    graph = ProjectGraph(
        nodes={
            "Constant1": Node(
                id="Constant1",
                type="Constant",
                name="Constant",
                position=(80, 80),
                params={"width": 8, "height": 4, "r": 0.25, "g": 0.5, "b": 0.75, "a": 1.0},
            ),
            "Write1": Node(
                id="Write1",
                type="Write",
                name="Write",
                position=(80, 220),
                params={"path": str(tmp_path / "render.####.png"), "overwrite": True},
            ),
        },
        edges=[Edge(id="e-constant-write", source_node="Constant1", target_node="Write1")],
    )
    script = ScriptTab(id="main", name="Comp 1", graph=graph, kind="comp")
    return Project(
        project_name="CLI Test",
        settings=ProjectSettings(frame_start=1001, frame_end=1002, width=8, height=4),
        graph=graph,
        script_tabs=[script],
        active_script_id="main",
    )


def _project_from_graph(graph: ProjectGraph) -> Project:
    script = ScriptTab(id="main", name="Comp 1", graph=graph, kind="comp")
    return Project(
        project_name="Nuke Export Test",
        settings=ProjectSettings(frame_start=1001, frame_end=1010, width=1920, height=1080),
        graph=graph,
        script_tabs=[script],
        active_script_id="main",
    )
