from __future__ import annotations

import hashlib
import json
import math
import re
from pathlib import Path
from typing import Any

from opencomp.core.models import Node, Project, ProjectGraph, ProjectSettings, ScriptTab
from opencomp.nodes import NODE_DEFINITIONS

NUKE_VERSION = "16.0 v6"
INPUT_ORDER_BY_TYPE = {definition.type.lower(): tuple(definition.inputs) for definition in NODE_DEFINITIONS}
MASK_SOCKETS = {"mask"}
SAFE_BARE_WORD = re.compile(r"^[A-Za-z0-9_./:%#+@=-]+$")


def export_nuke_script(project: Project, output_path: str | Path) -> Path:
    path = Path(output_path).expanduser()
    if path.suffix.lower() != ".nk":
        path = path.with_suffix(".nk")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(build_nuke_script(project, path), encoding="utf-8")
    return path


def build_nuke_script(project: Project, output_path: str | Path | None = None) -> str:
    active_script = _active_script(project)
    target_name = str(output_path or project.settings.project_path or project.project_name or "opencomp_export.nk")
    lines: list[str] = [
        f"version {NUKE_VERSION}",
        "# Generated by OpenComp Studio Nuke exporter v1.",
        "# This is a structural export: common nodes are mapped to native Nuke nodes;",
        "# unsupported OpenComp nodes are emitted as NoOp placeholders.",
        *_root_lines(project, target_name),
        "",
        f"# OpenComp active script: {active_script.id} ({active_script.name})",
    ]
    lines.extend(_graph_lines(active_script.graph, project.settings))
    return "\n".join(lines).rstrip() + "\n"


def _active_script(project: Project) -> ScriptTab:
    for tab in project.script_tabs:
        if tab.id == project.active_script_id:
            return tab
    if project.script_tabs:
        return project.script_tabs[0]
    return ScriptTab(id="main", name="Comp 1", graph=project.graph, kind="comp")


def _root_lines(project: Project, target_name: str) -> list[str]:
    settings = project.settings
    root_knobs: dict[str, Any] = {
        "inputs": 0,
        "name": _normalize_path(target_name),
        "frame": settings.frame_start,
        "first_frame": settings.frame_start,
        "last_frame": settings.frame_end,
        "lock_range": True,
        "format": _format_string(settings.width, settings.height, 1.0, _format_name(settings)),
        "proxy_type": "scale",
    }
    if settings.proxy_enabled:
        root_knobs["proxy_format"] = _format_string(
            settings.viewer_max_width,
            settings.viewer_max_height,
            1.0,
            f"proxy_{settings.viewer_max_width}x{settings.viewer_max_height}",
        )
    if settings.ocio_config or settings.working_colorspace or settings.viewer_view:
        root_knobs["colorManagement"] = "OCIO"
        if settings.ocio_config:
            root_knobs["OCIO_config"] = "custom"
            root_knobs["customOCIOConfigPath"] = _normalize_path(settings.ocio_config)
        root_knobs["workingSpaceLUT"] = _nuke_colorspace(settings.working_colorspace)
        if settings.viewer_display:
            root_knobs["monitorLut"] = settings.viewer_display
        if settings.viewer_view:
            root_knobs["monitorOutLUT"] = settings.viewer_view

    lines = ["Root {"]
    lines.extend(_knob_lines(root_knobs, indent=" "))
    lines.append("}")
    return lines


def _graph_lines(graph: ProjectGraph, settings: ProjectSettings) -> list[str]:
    ordered_nodes = _topological_nodes(graph)
    var_by_node: dict[str, str] = {}
    lines: list[str] = []
    for node in ordered_nodes:
        block = _nuke_block_for_node(node, settings)
        connections = _ordered_connections(graph, node)
        if block["node_class"] == "NoOp" and len(connections) > 1:
            lines.append(f"# OpenComp exporter: {node.id} has {len(connections)} inputs; NoOp fallback keeps the first.")
            connections = connections[:1]

        add_layer_lines = _add_layer_lines(node)
        lines.extend(add_layer_lines)
        for _, source_node in reversed(connections):
            if source_node is None:
                lines.append("push 0")
            else:
                source_var = var_by_node.get(source_node)
                if source_var is None:
                    lines.append(f"# OpenComp exporter warning: source {source_node} was not available for {node.id}.")
                    lines.append("push 0")
                else:
                    lines.append(f"push ${source_var}")

        block_knobs = {"inputs": _inputs_value(connections), **block["knobs"]}
        lines.extend(_node_block_lines(block["node_class"], block_knobs))
        variable_name = _stack_variable(node.id, var_by_node.values())
        lines.append(f"set {variable_name} [stack 0]")
        var_by_node[node.id] = variable_name
    return lines


def _topological_nodes(graph: ProjectGraph) -> list[Node]:
    incoming_count = {node_id: 0 for node_id in graph.nodes}
    outgoing: dict[str, list[str]] = {node_id: [] for node_id in graph.nodes}
    for edge in graph.edges:
        if edge.source_node not in graph.nodes or edge.target_node not in graph.nodes:
            continue
        incoming_count[edge.target_node] += 1
        outgoing[edge.source_node].append(edge.target_node)

    ready = sorted(
        (node_id for node_id, count in incoming_count.items() if count == 0),
        key=lambda node_id: _node_sort_key(graph.nodes[node_id]),
    )
    ordered: list[Node] = []
    while ready:
        node_id = ready.pop(0)
        ordered.append(graph.nodes[node_id])
        for target_id in sorted(outgoing[node_id], key=lambda item: _node_sort_key(graph.nodes[item])):
            incoming_count[target_id] -= 1
            if incoming_count[target_id] == 0:
                ready.append(target_id)
                ready.sort(key=lambda item: _node_sort_key(graph.nodes[item]))

    if len(ordered) != len(graph.nodes):
        remaining = [node_id for node_id in graph.nodes if node_id not in {node.id for node in ordered}]
        raise ValueError(f"Cannot export Nuke script from cyclic graph. Remaining nodes: {remaining}")
    return ordered


def _node_sort_key(node: Node) -> tuple[float, float, str]:
    return (float(node.position[1]), float(node.position[0]), node.id)


def _ordered_connections(graph: ProjectGraph, node: Node) -> list[tuple[str, str | None]]:
    incoming = _incoming_by_socket(graph, node.id)
    if not incoming:
        return []
    if node.type.lower() == "viewer":
        numeric = sorted(int(socket) for socket in incoming if socket.isdigit())
        if numeric:
            return [(str(index), incoming.get(str(index))) for index in range(max(numeric) + 1)]
    order = list(INPUT_ORDER_BY_TYPE.get(node.type.lower(), ()))
    order.extend(socket for socket in incoming if socket not in order)
    return [
        (socket, incoming.get(socket))
        for socket in order
        if socket in incoming or _needs_input_hole(socket, incoming, order)
    ]


def _needs_input_hole(socket: str, incoming: dict[str, str], order: list[str]) -> bool:
    if socket in MASK_SOCKETS:
        return socket in incoming
    try:
        socket_index = order.index(socket)
    except ValueError:
        return False
    connected_indices = [order.index(candidate) for candidate in incoming if candidate in order]
    return bool(connected_indices and socket_index < max(connected_indices))


def _incoming_by_socket(graph: ProjectGraph, node_id: str) -> dict[str, str]:
    result: dict[str, str] = {}
    for edge in graph.edges:
        if edge.target_node == node_id:
            result[str(edge.target_socket or "in")] = edge.source_node
    return result


def _inputs_value(connections: list[tuple[str, str | None]]) -> int | str:
    if not connections:
        return 0
    incoming_sockets = {socket for socket, _ in connections}
    if MASK_SOCKETS & incoming_sockets:
        base_count = max(1, len(connections) - 1)
        return f"{base_count}+1"
    return len(connections)


def _nuke_block_for_node(node: Node, settings: ProjectSettings) -> dict[str, Any]:
    node_type = node.type.lower()
    mapper = {
        "read": _read_knobs,
        "write": _write_knobs,
        "constant": _constant_knobs,
        "grade": _grade_knobs,
        "exposure": _exposure_knobs,
        "saturation": _saturation_knobs,
        "invert": _pass_through_knobs,
        "clamp": _clamp_knobs,
        "colorspace": _colorspace_knobs,
        "blur": _blur_knobs,
        "reformat": _reformat_knobs,
        "scale": _scale_knobs,
        "transform": _transform_knobs,
        "shuffle": _shuffle_knobs,
        "copy": _copy_knobs,
        "channelmerge": _channel_merge_knobs,
        "addchannels": _add_channels_knobs,
        "remove": _remove_knobs,
        "premult": _pass_through_knobs,
        "unpremult": _pass_through_knobs,
        "merge": _merge_knobs,
        "cryptomatte": _cryptomatte_knobs,
        "viewmetadata": _pass_through_knobs,
        "comparemetadata": _pass_through_knobs,
        "modifymetadata": _modify_metadata_knobs,
        "copymetadata": _pass_through_knobs,
        "addtimecode": _add_timecode_knobs,
        "viewer": _viewer_knobs,
    }.get(node_type)
    if mapper is None:
        return _unsupported_block(node, settings)
    node_class, knobs = mapper(node, settings)
    return {"node_class": node_class, "knobs": {**knobs, **_common_knobs(node, node_class)}}


def _common_knobs(node: Node, node_class: str) -> dict[str, Any]:
    x, y = node.position
    knobs: dict[str, Any] = {
        "name": _nuke_node_name(node.id),
        "xpos": int(round(x)),
        "ypos": int(round(y)),
    }
    if node.name and node.name not in {node.id, node.type, node_class}:
        knobs["label"] = node.name
    for source_key, nuke_key in (
        ("label", "label"),
        ("tile_color", "tile_color"),
        ("disable", "disable"),
        ("hide_input", "hide_input"),
        ("note_font_size", "note_font_size"),
    ):
        if source_key in node.params and nuke_key not in knobs:
            knobs[nuke_key] = node.params[source_key]
    return knobs


def _read_knobs(node: Node, settings: ProjectSettings) -> tuple[str, dict[str, Any]]:
    path = str(node.params.get("path") or node.params.get("file") or "")
    knobs: dict[str, Any] = {
        "file_type": node.params.get("file_type") or _file_type(path),
        "file": _normalize_path(path),
    }
    if node.params.get("format"):
        knobs["format"] = node.params["format"]
    if node.params.get("width") and node.params.get("height"):
        knobs["format"] = _format_string(int(node.params["width"]), int(node.params["height"]), float(node.params.get("pixel_aspect", 1.0)), "")
    first = node.params.get("frame_start", node.params.get("first"))
    last = node.params.get("frame_end", node.params.get("last"))
    if first is not None:
        knobs["first"] = int(first)
        knobs["origfirst"] = int(first)
    if last is not None:
        knobs["last"] = int(last)
        knobs["origlast"] = int(last)
    if first is not None or last is not None:
        knobs["origset"] = True
    for key in ("before", "after", "frame_mode", "frame", "on_error"):
        if key in node.params and node.params[key] not in {None, ""}:
            knobs[key] = node.params[key]
    colorspace = node.params.get("colorspace") or node.params.get("input_transform") or settings.working_colorspace
    if colorspace:
        knobs["colorspace"] = _nuke_colorspace(str(colorspace))
    if bool(node.params.get("auto_alpha", False)):
        knobs["auto_alpha"] = True
    return "Read", knobs


def _write_knobs(node: Node, settings: ProjectSettings) -> tuple[str, dict[str, Any]]:
    path = str(node.params.get("path") or node.params.get("file") or settings.default_output_path)
    knobs: dict[str, Any] = {
        "channels": node.params.get("channels") or "rgba",
        "file": _normalize_path(path),
        "file_type": node.params.get("file_type") or _file_type(path),
    }
    if node.params.get("datatype"):
        knobs["datatype"] = node.params["datatype"]
    if node.params.get("compression"):
        knobs["compression"] = node.params["compression"]
    if node.params.get("colorspace") or node.params.get("output_transform"):
        knobs["colorspace"] = _nuke_colorspace(str(node.params.get("colorspace") or node.params.get("output_transform")))
    if node.params.get("create_directories") is not None:
        knobs["create_directories"] = bool(node.params["create_directories"])
    if node.params.get("limit_to_range"):
        knobs["use_limit"] = True
        knobs["first"] = int(node.params.get("frame_start") or node.params.get("first") or settings.frame_start)
        knobs["last"] = int(node.params.get("frame_end") or node.params.get("last") or settings.frame_end)
    return "Write", knobs


def _constant_knobs(node: Node, settings: ProjectSettings) -> tuple[str, dict[str, Any]]:
    width = int(node.params.get("width") or settings.width)
    height = int(node.params.get("height") or settings.height)
    color = [
        float(node.params.get("r", 0.0)),
        float(node.params.get("g", 0.0)),
        float(node.params.get("b", 0.0)),
        float(node.params.get("a", 1.0)),
    ]
    return "Constant", {
        "channels": node.params.get("channels") or "rgba",
        "format": _format_string(width, height, float(node.params.get("pixel_aspect", 1.0)), f"OpenComp_{width}x{height}"),
        "color": color,
    }


def _grade_knobs(node: Node, settings: ProjectSettings) -> tuple[str, dict[str, Any]]:
    gain = float(node.params.get("gain", 1.0)) * float(node.params.get("multiply", 1.0))
    add = float(node.params.get("offset", 0.0)) + float(node.params.get("add", 0.0))
    knobs: dict[str, Any] = {}
    if gain != 1.0:
        knobs["multiply"] = gain
    if add != 0.0:
        knobs["add"] = add
    if float(node.params.get("gamma", 1.0)) != 1.0:
        knobs["gamma"] = node.params["gamma"]
    for key in ("blackpoint", "whitepoint", "black", "white", "mix", "channels", "black_clamp", "white_clamp"):
        if key in node.params:
            knobs[key] = node.params[key]
    return "Grade", knobs


def _exposure_knobs(node: Node, settings: ProjectSettings) -> tuple[str, dict[str, Any]]:
    stops = float(node.params.get("stops", node.params.get("fstop", node.params.get("exposure", 0.0))))
    return "Grade", {"multiply": 2.0**stops, "label": f"OpenComp Exposure {stops:g} stops"}


def _saturation_knobs(node: Node, settings: ProjectSettings) -> tuple[str, dict[str, Any]]:
    return "Saturation", {"saturation": node.params.get("saturation", 1.0)}


def _clamp_knobs(node: Node, settings: ProjectSettings) -> tuple[str, dict[str, Any]]:
    return "Clamp", {
        "channels": node.params.get("channels", "rgba"),
        "minimum": node.params.get("minimum", node.params.get("min", 0.0)),
        "maximum": node.params.get("maximum", node.params.get("max", 1.0)),
    }


def _colorspace_knobs(node: Node, settings: ProjectSettings) -> tuple[str, dict[str, Any]]:
    return "OCIOColorSpace", {
        "in_colorspace": _nuke_colorspace(str(node.params.get("src") or settings.working_colorspace)),
        "out_colorspace": _nuke_colorspace(str(node.params.get("dst") or settings.working_colorspace)),
    }


def _blur_knobs(node: Node, settings: ProjectSettings) -> tuple[str, dict[str, Any]]:
    return "Blur", {"channels": node.params.get("channels", "rgba"), "size": node.params.get("radius", node.params.get("size", 1.0))}


def _reformat_knobs(node: Node, settings: ProjectSettings) -> tuple[str, dict[str, Any]]:
    width = int(node.params.get("width") or settings.width)
    height = int(node.params.get("height") or settings.height)
    return "Reformat", {
        "format": node.params.get("format") or _format_string(width, height, float(node.params.get("pixel_aspect", 1.0)), f"OpenComp_{width}x{height}"),
        "resize": node.params.get("resize", "distort"),
        "pbb": bool(node.params.get("pbb", node.params.get("preserve_bbox", False))),
    }


def _scale_knobs(node: Node, settings: ProjectSettings) -> tuple[str, dict[str, Any]]:
    return "Transform", {"scale": node.params.get("scale", 1.0), "center": [settings.width / 2, settings.height / 2]}


def _transform_knobs(node: Node, settings: ProjectSettings) -> tuple[str, dict[str, Any]]:
    return "Transform", {
        "translate": [node.params.get("translate_x", 0.0), node.params.get("translate_y", 0.0)],
        "scale": node.params.get("scale", 1.0),
        "center": node.params.get("center", [settings.width / 2, settings.height / 2]),
    }


def _shuffle_knobs(node: Node, settings: ProjectSettings) -> tuple[str, dict[str, Any]]:
    knobs = {"in": node.params.get("in", node.params.get("input_layer", "rgba"))}
    for key in ("out", "alpha", "red", "green", "blue", "black", "white", "red2", "green2", "blue2", "alpha2", "out2"):
        if key in node.params:
            knobs[key] = node.params[key]
    return "Shuffle", knobs


def _copy_knobs(node: Node, settings: ProjectSettings) -> tuple[str, dict[str, Any]]:
    knobs: dict[str, Any] = {"channels": node.params.get("channels", node.params.get("layer_copy", "none"))}
    pairs = _copy_pairs(node)
    for index, (source, target) in enumerate(pairs[:4]):
        knobs[f"from{index}"] = source
        knobs[f"to{index}"] = target
    for key in ("bbox", "mix", "invert_mask", "maskChannelMask", "fringe"):
        if key in node.params:
            knobs[key] = node.params[key]
    return "Copy", knobs


def _channel_merge_knobs(node: Node, settings: ProjectSettings) -> tuple[str, dict[str, Any]]:
    return "ChannelMerge", {
        "operation": node.params.get("operation", "union"),
        "Achannels": node.params.get("a_channel", node.params.get("A", "rgba.alpha")),
        "Bchannels": node.params.get("b_channel", node.params.get("B", "rgba.alpha")),
        "output": node.params.get("output", "rgba.alpha"),
        "mix": node.params.get("mix", 1.0),
    }


def _add_channels_knobs(node: Node, settings: ProjectSettings) -> tuple[str, dict[str, Any]]:
    return "AddChannels", {"channels": node.params.get("channels", "none"), "color": node.params.get("color", 0.0)}


def _remove_knobs(node: Node, settings: ProjectSettings) -> tuple[str, dict[str, Any]]:
    return "Remove", {"operation": node.params.get("operation", "remove"), "channels": node.params.get("channels", "all")}


def _merge_knobs(node: Node, settings: ProjectSettings) -> tuple[str, dict[str, Any]]:
    operation = str(node.params.get("operation") or "over").lower()
    if operation == "add":
        operation = "plus"
    knobs: dict[str, Any] = {
        "operation": operation,
        "bbox": _bbox_mode(node.params.get("bbox", node.params.get("set_bbox", "union"))),
        "Achannels": node.params.get("a_channels", node.params.get("Achannels", "rgba")),
        "Bchannels": node.params.get("b_channels", node.params.get("Bchannels", "rgba")),
        "output": node.params.get("output", "rgba"),
    }
    for key in ("also_merge", "mix", "invert_mask", "fringe"):
        if key in node.params:
            knobs[key] = node.params[key]
    if node.params.get("metadata_from"):
        knobs["metainput"] = str(node.params["metadata_from"]).upper()
    if node.params.get("range_from"):
        knobs["rangeinput"] = str(node.params["range_from"]).upper()
    return "Merge2", knobs


def _cryptomatte_knobs(node: Node, settings: ProjectSettings) -> tuple[str, dict[str, Any]]:
    knobs: dict[str, Any] = {}
    if node.params.get("matte_ids"):
        value = node.params["matte_ids"]
        knobs["matteList"] = "\n".join(value) if isinstance(value, list) else str(value)
    if node.params.get("layer"):
        knobs["lastSelectedCryptoLayerName"] = node.params["layer"]
    return "Cryptomatte", knobs


def _modify_metadata_knobs(node: Node, settings: ProjectSettings) -> tuple[str, dict[str, Any]]:
    return "ModifyMetaData", {"label": "OpenComp ModifyMetadata"}


def _add_timecode_knobs(node: Node, settings: ProjectSettings) -> tuple[str, dict[str, Any]]:
    return "AddTimeCode", {"startcode": node.params.get("start_frame", settings.frame_start)}


def _viewer_knobs(node: Node, settings: ProjectSettings) -> tuple[str, dict[str, Any]]:
    knobs: dict[str, Any] = {"frame": settings.frame_start, "frame_range": f"{settings.frame_start}-{settings.frame_end}"}
    if settings.viewer_view:
        knobs["viewerProcess"] = settings.viewer_view
    if node.params.get("active_input"):
        knobs["input_number"] = node.params["active_input"]
    return "Viewer", knobs


def _pass_through_knobs(node: Node, settings: ProjectSettings) -> tuple[str, dict[str, Any]]:
    nuke_class = {
        "invert": "Invert",
        "premult": "Premult",
        "unpremult": "Unpremult",
        "viewmetadata": "ViewMetaData",
        "comparemetadata": "CompareMetaData",
        "copymetadata": "CopyMetaData",
    }.get(node.type.lower(), node.type)
    knobs = {key: node.params[key] for key in ("channels", "mix", "operation") if key in node.params}
    return nuke_class, knobs


def _unsupported_block(node: Node, settings: ProjectSettings) -> dict[str, Any]:
    label = f"OpenComp unsupported node: {node.type}"
    if node.params:
        compact = json.dumps(node.params, default=str, sort_keys=True)
        label = f"{label}\\n{compact[:220]}"
    return {
        "node_class": "NoOp",
        "knobs": {**_common_knobs(node, "NoOp"), "label": label},
    }


def _node_block_lines(node_class: str, knobs: dict[str, Any]) -> list[str]:
    lines = [f"{node_class} {{"]
    lines.extend(_knob_lines(knobs, indent=" "))
    lines.append("}")
    return lines


def _knob_lines(knobs: dict[str, Any], indent: str = " ") -> list[str]:
    lines: list[str] = []
    for key, value in knobs.items():
        if value is None:
            continue
        lines.append(f"{indent}{key} {_format_value(value)}")
    return lines


def _format_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        if math.isfinite(value):
            return f"{value:.10g}"
        return "0"
    if isinstance(value, (list, tuple)):
        return "{" + " ".join(_format_value(item) for item in value) + "}"
    text = str(value)
    if text == "":
        return '""'
    if SAFE_BARE_WORD.match(text) and not text.startswith("#"):
        return text
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def _format_string(width: int, height: int, pixel_aspect: float, name: str) -> str:
    label = name or f"OpenComp_{width}x{height}"
    return f"{int(width)} {int(height)} 0 0 {int(width)} {int(height)} {pixel_aspect:g} {label}"


def _format_name(settings: ProjectSettings) -> str:
    return f"OpenComp_{settings.width}x{settings.height}"


def _file_type(path: str) -> str:
    suffix = Path(path.replace("\\", "/")).suffix.lower().lstrip(".")
    return {"jpg": "jpeg", "jpeg": "jpeg", "tif": "tiff", "tiff": "tiff"}.get(suffix, suffix or "exr")


def _normalize_path(path: str) -> str:
    return str(path).replace("\\", "/")


def _nuke_colorspace(value: str) -> str:
    normalized = value.strip()
    lower = normalized.lower()
    mapping = {
        "aces2065-1": "ACES - ACES2065-1",
        "aces - aces2065-1": "ACES - ACES2065-1",
        "acescg": "ACES - ACEScg",
        "aces - acescg": "ACES - ACEScg",
        "srgb": "Output - sRGB",
        "sRGB": "Output - sRGB",
        "rec.709": "Output - Rec.709",
        "rec709": "Output - Rec.709",
        "scene-linear": "scene_linear",
        "scene_linear": "scene_linear",
    }
    return mapping.get(lower, normalized)


def _bbox_mode(value: Any) -> str:
    normalized = str(value).lower()
    if normalized in {"a", "b"}:
        return normalized.upper()
    if normalized in {"intersection", "intersect"}:
        return "intersection"
    return normalized or "union"


def _nuke_node_name(node_id: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_]", "_", node_id).strip("_")
    if not cleaned:
        cleaned = "OpenCompNode"
    if cleaned[0].isdigit():
        cleaned = f"OC_{cleaned}"
    return cleaned


def _stack_variable(node_id: str, existing: Any) -> str:
    base = "OC_" + re.sub(r"[^A-Za-z0-9_]", "_", node_id).strip("_")
    if not base or base == "OC_":
        base = "OC_" + hashlib.sha1(node_id.encode("utf-8")).hexdigest()[:8]
    if base[3:4].isdigit():
        base = "OCN_" + base[3:]
    existing_set = set(existing)
    candidate = base
    suffix = 2
    while candidate in existing_set:
        candidate = f"{base}_{suffix}"
        suffix += 1
    return candidate


def _copy_pairs(node: Node) -> list[tuple[str, str]]:
    pairs: list[tuple[str, str]] = []
    if "from" in node.params or "to" in node.params:
        pairs.append((str(node.params.get("from", "rgba.alpha")), str(node.params.get("to", "rgba.alpha"))))
    for index in range(4):
        source = node.params.get(f"from{index}")
        target = node.params.get(f"to{index}")
        if source and target and str(source).lower() != "none" and str(target).lower() != "none":
            pairs.append((str(source), str(target)))
    return pairs


def _add_layer_lines(node: Node) -> list[str]:
    layers: set[str] = set()
    for value in node.params.values():
        if isinstance(value, str):
            for match in re.finditer(r"\b([A-Za-z][A-Za-z0-9_]*)\.(red|green|blue|alpha|z)\b", value):
                layer = match.group(1)
                if layer != "rgba":
                    layers.add(layer)
    return [f"add_layer {{{layer} {layer}.red {layer}.green {layer}.blue {layer}.alpha}}" for layer in sorted(layers)]
